# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies library
      run: dotnet restore ./src/Library/
    - name: Build library
      run: dotnet build --no-restore ./src/Library/
      
    - name: Restore dependencies unit tests
      run: dotnet restore ./src/UnitTests/
    - name: Build unit tests
      run: dotnet build --no-restore ./src/UnitTests/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/UnitTests/
